version: "2"

services:
  client:
    container_name: "basic-app-client"
    build:
      context: "../client/"
      dockerfile: "Dockerfile"
    volumes:
      - ../client:/app
      - /app/node_modules
    depends_on:
      - backend-app

  backend-web:
    container_name: "basic-app-backend-web"
    build:
      context: "../backend-web/"
      dockerfile: "Dockerfile"
    ports:
      - "80:80"
    depends_on:
      - client
      - backend-app

  backend-app:
    container_name: "basic-app-backend-app"
    build:
      context: "../backend-app/"
      dockerfile: "Dockerfile"
    volumes:
      - ../backend-app:/app
      - /app/node_modules
    depends_on:
      - backend-db

  backend-db:
    container_name: "basic-app-backend-db"
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    restart: "always"
